"""
Per-instance GitHub credentials.

Each worker registers against its own repository or organisation under its own
name, so each one needs its own credential. There is no global token: a single
shared secret would make two instances pointed at different orgs impossible,
which is the whole reason instances exist.

    /etc/gh-runner/credentials.d/<id>  --[ set-credential | sync ]-->  podman
            0600, root-only                          secret gh-runner-token-<id>

The file is the source of truth; the secret is derived state, regenerated by
`sync` like every other derived artifact. The service account never reads the
file — ctl runs as root and pipes the value straight into
`podman secret create`, so the credential does not need to be readable by the
uid that runs the containers.

`podman secret create` cannot update in place, so sync removes and recreates.
A container already running keeps the old value until its next start, which is
the usual job-boundary behaviour and needs no special handling.

author: Christopher O'Brien <obriencj@gmail.com>
license: GPLv3
"""

import hashlib
import os
import stat
from pathlib import Path

from . import CREDENTIALS_DIR, SECRET_PREFIX, CtlError
from ._run import podman, podman_json


_LABEL = "net.preoccupied.gh-runner.digest"


def credential_path(iid: str) -> Path:
    return CREDENTIALS_DIR / iid


def secret_name(iid: str) -> str:
    return f"{SECRET_PREFIX}-{iid}"


def has_credential(iid: str) -> bool:
    p = credential_path(iid)
    return p.exists() and p.stat().st_size > 0


def read_credential(iid: str) -> str:
    """
    Read one instance's credential, refusing an over-permissive file
    """

    p = credential_path(iid)
    if not has_credential(iid):
        raise CtlError(
            f"no credential for instance {iid} at {p}\n"
            f"run: gh-runner-ctl set-credential {iid}"
        )

    mode = stat.S_IMODE(p.stat().st_mode)
    if mode & 0o077:
        raise CtlError(
            f"{p} is mode {mode:04o}; must not be group- or world-readable. "
            f"Fix with: chmod 0600 {p}"
        )

    return p.read_text().strip()


def write_credential(iid: str, value: str) -> None:
    value = value.strip()
    if not value:
        raise CtlError("refusing to write an empty credential")

    CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
    os.chmod(CREDENTIALS_DIR, 0o700)

    # Created 0600 from the start; never widened and then narrowed.
    p = credential_path(iid)
    fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(value + "\n")
    os.chmod(p, 0o600)


def _digest(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()[:16]


def _secrets() -> dict[str, str | None]:
    """
    Every gh-runner secret podman knows about, mapped to its digest label
    """

    out: dict[str, str | None] = {}
    for entry in podman_json("secret", "ls"):
        name = entry.get("Name") or ""
        if not name.startswith(f"{SECRET_PREFIX}-"):
            continue
        labels = (entry.get("Spec") or {}).get("Labels") or entry.get("Labels") or {}
        out[name] = labels.get(_LABEL)
    return out


def _inspect(iid: str) -> tuple[bool, str | None]:
    """
    (secret exists, its digest label) in one call, via a Go template.

    Deliberately not JSON. `add` and `enable` run this on every invocation and
    have no business depending on podman's output format -- a stray warning
    line on stdout was enough to break `enable` outright. Exit status answers
    "does it exist" and the template answers "what digest", neither of which
    can be derailed by prose.
    """

    proc = podman(
        "secret", "inspect", secret_name(iid),
        "--format", "{{index .Spec.Labels \"" + _LABEL + "\"}}",
        check=False,
    )
    if proc.returncode != 0:
        return False, None

    out = proc.stdout.strip()
    # An unlabelled secret -- created by hand, or by a version that did not
    # label them. Exists, but its contents cannot be compared.
    if not out or out == "<no value>":
        return True, None
    return True, out


def secret_exists(iid: str) -> bool:
    return _inspect(iid)[0]


def sync(iid: str) -> bool:
    """
    Make one instance's podman secret match its file. True if it changed
    """

    value = read_credential(iid)
    want = _digest(value)
    name = secret_name(iid)

    exists, have = _inspect(iid)
    if exists:
        if have == want:
            return False
        # Different, or unlabelled and therefore unknowable. podman cannot
        # update a secret in place, so replace it. A running container keeps
        # the old value until its next job boundary.
        podman("secret", "rm", name, check=False)

    podman(
        "secret", "create",
        "--label", f"{_LABEL}={want}",
        name, "-",
        stdin=value,
    )
    return True


def remove(iid: str) -> bool:
    """
    Drop an instance's credential file and its secret
    """

    changed = False

    if secret_exists(iid):
        podman("secret", "rm", secret_name(iid), check=False)
        changed = True

    p = credential_path(iid)
    if p.exists():
        p.unlink()
        changed = True

    return changed


def prune_orphan_secrets(known: set[str]) -> list[str]:
    """
    Remove secrets for instances that no longer have a conf file
    """

    dropped = []
    wanted = {secret_name(iid) for iid in known}
    for name in _secrets():
        if name not in wanted:
            podman("secret", "rm", name, check=False)
            dropped.append(name)
    return dropped


def orphan_credentials(known: set[str]) -> list[str]:
    """
    Credential files with no matching instance. Reported, never deleted --
    removing a token because a conf file went missing is not recoverable.
    """

    if not CREDENTIALS_DIR.is_dir():
        return []
    return sorted(p.name for p in CREDENTIALS_DIR.iterdir()
                  if p.is_file() and p.name not in known)


# The end.
