"""
Unit management: Quadlet symlinks, generated drop-ins, and the enable/disable
verbs.

Drop-ins are written to /etc/systemd/user/gh-runner@<id>.service.d/ — the
*generated service*, not the .container file. systemd applies drop-ins from
its own unit path to generator-produced units, which gives unambiguous
per-instance scoping; Quadlet's handling of instance-specific .container.d
drop-ins for a template is the sort of thing that works until it doesn't.

Everything here is derived state. `sync` regenerates rather than assuming
current, so a hand-edited conf becomes real on the next sync.
"""

from pathlib import Path

from . import QUADLET_SRC, QUADLET_USER_DIR, SYSTEMD_USER_DIR, CtlError
from ._run import daemon_reload, service_uid, systemctl
from .conf import Instance


DROPIN_NAME = "limits.conf"
GENERATED_HEADER = (
    "# Generated by gh-runner-ctl sync. Do not edit.\n"
    "# Source: {source}\n"
    "# Edit the conf file and re-run `gh-runner-ctl sync`.\n"
)


def quadlet_dir() -> Path:
    return QUADLET_USER_DIR / str(service_uid())


def dropin_dir(inst: Instance) -> Path:
    return SYSTEMD_USER_DIR / f"{inst.unit}.d"


def render_dropin(inst: Instance) -> str | None:
    """
    None when the instance sets no unit-shaping keys
    """

    shaping = inst.unit_shaping()
    if not shaping:
        return None
    body = "".join(f"{k}={v}\n" for k, v in sorted(shaping.items()))
    return GENERATED_HEADER.format(source=inst.path) + "\n[Service]\n" + body


def sync_dropin(inst: Instance) -> bool:
    """
    Write or remove the drop-in. True if anything changed
    """

    d = dropin_dir(inst)
    target = d / DROPIN_NAME
    wanted = render_dropin(inst)

    if wanted is None:
        if target.exists():
            target.unlink()
            _prune_empty(d)
            return True
        return False

    current = target.read_text() if target.exists() else None
    if current == wanted:
        return False

    d.mkdir(parents=True, exist_ok=True)
    target.write_text(wanted)
    return True


def _prune_empty(d: Path) -> None:
    try:
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
    except OSError:
        pass


def sync_quadlet_links() -> bool:
    """
    Keep the Quadlet symlinks pointing at the package's units
    """

    qdir = quadlet_dir()
    if not QUADLET_SRC.is_dir():
        raise CtlError(f"missing {QUADLET_SRC}; package install is incomplete")

    changed = False
    qdir.mkdir(parents=True, exist_ok=True)
    wanted = {p.name: p for p in QUADLET_SRC.iterdir() if p.is_file()}

    for name, src in wanted.items():
        link = qdir / name
        if link.is_symlink() and link.readlink() == src:
            continue
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(src)
        changed = True

    for link in qdir.iterdir():
        if link.name not in wanted:
            link.unlink()
            changed = True

    return changed


def prune_orphan_dropins(known: set[str]) -> bool:
    """
    Remove drop-ins for instances whose conf file has gone away
    """

    changed = False
    if not SYSTEMD_USER_DIR.is_dir():
        return False
    for d in SYSTEMD_USER_DIR.glob("gh-runner@*.service.d"):
        iid = d.name[len("gh-runner@") : -len(".service.d")]
        if iid not in known:
            for f in d.iterdir():
                f.unlink()
            d.rmdir()
            changed = True
    return changed


TARGET = "gh-runner.target"
WANTS_DIR = f"{TARGET}.wants"


def _wants_link(inst: Instance) -> Path:
    return SYSTEMD_USER_DIR / WANTS_DIR / inst.unit


def fragment_path(inst: Instance) -> str | None:
    """
    Where systemd currently loads this unit's definition from.

    For a Quadlet template that is the generated template file, e.g.
    /run/user/987/systemd/generator/gh-runner@.service. Asked rather than
    assumed: the generator directory is not ours to hardcode.
    """

    proc = systemctl("show", inst.unit, "--property=FragmentPath", check=False)
    for line in proc.stdout.splitlines():
        key, _, value = line.partition("=")
        if key == "FragmentPath" and value:
            return value
    return None


def is_enabled(inst: Instance) -> bool:
    return _wants_link(inst).is_symlink()


def migrate_wants() -> list[str]:
    """
    Move instance links from default.target.wants to gh-runner.target.wants.

    Earlier builds linked instances straight into default.target, which starts
    them at boot but leaves them outside the aggregate target -- so
    `systemctl stop gh-runner.target` would silently miss them.
    """

    moved = []
    old = SYSTEMD_USER_DIR / "default.target.wants"
    if not old.is_dir():
        return moved

    new = SYSTEMD_USER_DIR / WANTS_DIR
    for link in sorted(old.glob("gh-runner@*.service")):
        new.mkdir(parents=True, exist_ok=True)
        target = link.readlink() if link.is_symlink() else None
        link.unlink()
        if target is not None:
            dest = new / link.name
            if dest.is_symlink() or dest.exists():
                dest.unlink()
            dest.symlink_to(target)
        moved.append(link.name)
    return moved


#: Shipped in %{_userunitdir}, WantedBy=gh-runner.target. Real unit files,
#: not generated, so systemctl enable works on these normally.
TIMERS = (
    "gh-runner-prune.timer",
    "gh-runner-image-refresh.timer",
    "gh-runner-version-check.timer",
)


def ensure_podman_socket() -> bool:
    """
    podman.socket must be enabled and running before any instance starts.

    The mount source is /run/user/<uid>/podman/podman.sock. If the socket unit
    has never run that path does not exist, and podman — asked to bind-mount a
    missing source — creates a *directory* there. The container then finds a
    directory at /var/run/docker.sock, and the failure reads "is not a socket"
    rather than anything about podman.socket.

    %post tries to enable it, but with `|| :`, so a failure there says nothing.
    This is the converge step that has to actually hold.
    """

    changed = False
    sock = Path(f"/run/user/{service_uid()}/podman/podman.sock")

    # Podman's leftover directory keeps shadowing the real socket until it goes.
    if sock.is_dir():
        try:
            sock.rmdir()
            changed = True
        except OSError as exc:
            raise CtlError(
                f"{sock} is a directory, not a socket — podman created it when "
                f"the mount source was missing — and it could not be removed: "
                f"{exc}"
            ) from exc

    if systemctl("is-enabled", "podman.socket", check=False).stdout.strip() != "enabled":
        systemctl("enable", "podman.socket")
        changed = True

    if systemctl("is-active", "podman.socket", check=False).stdout.strip() != "active":
        systemctl("start", "podman.socket")
        changed = True

    return changed


def sync_timers() -> list[str]:
    """
    Enable the maintenance timers.

    Nothing else did. They were shipped and never enabled, so pruning, image
    refresh and the version-floor check silently never ran. Asked of systemd
    rather than inferred from a symlink, because `systemctl enable` writes into
    the account's own config directory, not the one we manage.
    """

    changed = []
    for timer in TIMERS:
        proc = systemctl("is-enabled", timer, check=False)
        if proc.stdout.strip() != "enabled":
            systemctl("enable", timer)
            changed.append(timer)
    return changed


def start_all() -> None:
    systemctl("start", TARGET)


def stop_all() -> None:
    systemctl("stop", TARGET)


def restart_all() -> None:
    systemctl("restart", TARGET)


def start(inst: Instance) -> None:
    systemctl("start", inst.unit)


def stop(inst: Instance) -> None:
    systemctl("stop", inst.unit, check=False)


def enable(inst: Instance, now: bool = True) -> None:
    """
    Enable a Quadlet template instance.

    `systemctl enable` cannot do this:

        Failed to enable unit: Unit /run/user/987/systemd/generator/
        gh-runner@.service is transient or generated

    Quadlet's units are generated, and systemd refuses to enable a generated
    unit — its own mechanism is the [Install] section in the .container file,
    which a *template* cannot use per instance because WantedBy= there
    instantiates nothing without a DefaultInstance.

    So we write what `systemctl enable` would have written for any template
    unit: a .wants symlink named for the instance, pointing at the template
    fragment. systemd resolves the dependency from the link's name and loads
    the unit through its normal search path.
    """

    frag = fragment_path(inst)
    if not frag:
        raise CtlError(
            f"systemd does not know {inst.unit}.\n"
            f"Quadlet has not generated it — check `gh-runner-ctl doctor` and "
            f"that {inst.path.name} is valid, then `gh-runner-ctl sync`."
        )

    link = _wants_link(inst)
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(frag)

    daemon_reload()
    if now:
        systemctl("start", inst.unit)


def disable(inst: Instance, now: bool = False) -> None:
    link = _wants_link(inst)
    if link.is_symlink() or link.exists():
        link.unlink()
        daemon_reload()
    if now:
        systemctl("stop", inst.unit, check=False)


def restart(inst: Instance) -> None:
    systemctl("restart", inst.unit)


def state(inst: Instance) -> dict[str, str]:
    proc = systemctl(
        "show",
        inst.unit,
        "--property=ActiveState",
        "--property=UnitFileState",
        "--property=SubState",
        "--property=NRestarts",
        "--property=Result",
        "--property=ExecMainStatus",
        check=False,
    )
    out: dict[str, str] = {}
    for line in proc.stdout.splitlines():
        key, _, value = line.partition("=")
        out[key] = value
    return out


def reload() -> None:
    daemon_reload()


# The end.
