"""
Unit management: Quadlet symlinks, generated drop-ins, and the enable/disable
verbs.

Drop-ins are written to /etc/systemd/user/gh-runner@<id>.service.d/ — the
*generated service*, not the .container file. systemd applies drop-ins from
its own unit path to generator-produced units, which gives unambiguous
per-instance scoping; Quadlet's handling of instance-specific .container.d
drop-ins for a template is the sort of thing that works until it doesn't.

Everything here is derived state. `sync` regenerates rather than assuming
current, so a hand-edited conf becomes real on the next sync.
"""

from pathlib import Path

from . import QUADLET_SRC, QUADLET_USER_DIR, SYSTEMD_USER_DIR, CtlError
from ._run import daemon_reload, service_uid, systemctl
from .conf import Instance


DROPIN_NAME = "limits.conf"
GENERATED_HEADER = (
    "# Generated by gh-runner-ctl sync. Do not edit.\n"
    "# Source: {source}\n"
    "# Edit the conf file and re-run `gh-runner-ctl sync`.\n"
)


def quadlet_dir() -> Path:
    return QUADLET_USER_DIR / str(service_uid())


def dropin_dir(inst: Instance) -> Path:
    return SYSTEMD_USER_DIR / f"{inst.unit}.d"


def render_dropin(inst: Instance) -> str | None:
    """
    None when the instance sets no unit-shaping keys
    """

    shaping = inst.unit_shaping()
    if not shaping:
        return None
    body = "".join(f"{k}={v}\n" for k, v in sorted(shaping.items()))
    return GENERATED_HEADER.format(source=inst.path) + "\n[Service]\n" + body


def sync_dropin(inst: Instance) -> bool:
    """
    Write or remove the drop-in. True if anything changed
    """

    d = dropin_dir(inst)
    target = d / DROPIN_NAME
    wanted = render_dropin(inst)

    if wanted is None:
        if target.exists():
            target.unlink()
            _prune_empty(d)
            return True
        return False

    current = target.read_text() if target.exists() else None
    if current == wanted:
        return False

    d.mkdir(parents=True, exist_ok=True)
    target.write_text(wanted)
    return True


def _prune_empty(d: Path) -> None:
    try:
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
    except OSError:
        pass


def sync_quadlet_links() -> bool:
    """
    Keep the Quadlet symlinks pointing at the package's units
    """

    qdir = quadlet_dir()
    if not QUADLET_SRC.is_dir():
        raise CtlError(f"missing {QUADLET_SRC}; package install is incomplete")

    changed = False
    qdir.mkdir(parents=True, exist_ok=True)
    wanted = {p.name: p for p in QUADLET_SRC.iterdir() if p.is_file()}

    for name, src in wanted.items():
        link = qdir / name
        if link.is_symlink() and link.readlink() == src:
            continue
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(src)
        changed = True

    for link in qdir.iterdir():
        if link.name not in wanted:
            link.unlink()
            changed = True

    return changed


def prune_orphan_dropins(known: set[str]) -> bool:
    """
    Remove drop-ins for instances whose conf file has gone away
    """

    changed = False
    if not SYSTEMD_USER_DIR.is_dir():
        return False
    for d in SYSTEMD_USER_DIR.glob("gh-runner@*.service.d"):
        iid = d.name[len("gh-runner@") : -len(".service.d")]
        if iid not in known:
            for f in d.iterdir():
                f.unlink()
            d.rmdir()
            changed = True
    return changed


def enable(inst: Instance, now: bool = True) -> None:
    systemctl("enable", inst.unit)
    if now:
        systemctl("start", inst.unit)


def disable(inst: Instance, now: bool = False) -> None:
    systemctl("disable", inst.unit, check=False)
    if now:
        systemctl("stop", inst.unit, check=False)


def restart(inst: Instance) -> None:
    systemctl("restart", inst.unit)


def state(inst: Instance) -> dict[str, str]:
    proc = systemctl(
        "show",
        inst.unit,
        "--property=ActiveState",
        "--property=UnitFileState",
        "--property=SubState",
        "--property=NRestarts",
        check=False,
    )
    out: dict[str, str] = {}
    for line in proc.stdout.splitlines():
        key, _, value = line.partition("=")
        out[key] = value
    return out


def reload() -> None:
    daemon_reload()


# The end.
